export function Footer({ storeName, area, industry }: { storeName: string; area: string; industry: string }) {
  return (
    <footer className="border-t border-gray-100 bg-white py-10">
      <div className="mx-auto flex max-w-6xl flex-col items-center gap-3 px-4 text-center sm:px-6 lg:px-8">
        <p className="text-base font-bold text-gray-900">{storeName}</p>
        <p className="text-xs text-gray-500 sm:text-sm">
          {area} ・ {industry}
        </p>
        <a href="#top" className="text-xs text-brand-600 hover:underline sm:text-sm">
          ページの先頭へ戻る ↑
        </a>
        <p className="mt-4 text-xs text-gray-400">
          © {new Date().getFullYear()} {storeName}. Generated by Neumos AI.
        </p>
      </div>
    </footer>
  );
}
