// ダミー店舗データ（開発・デモ用）
// 実在店舗を模した架空データです

import type { StoreInput } from '@/types'

export const DUMMY_STORES: StoreInput[] = [
  {
    place_id: 'dummy-001',
    name: '食堂あじさい',
    category: '飲食店',
    address: '沖縄県那覇市牧志2-1-1',
    phone: '098-111-0001',
    opening_hours: { weekday_text: ['月曜日: 11:00–21:00', '火曜日: 11:00–21:00', '水曜日: 定休日', '木曜日: 11:00–21:00', '金曜日: 11:00–21:00', '土曜日: 11:00–22:00', '日曜日: 11:00–20:00'] },
    rating: 4.3,
    review_count: 87,
    photo_count: 24,
    website_url: null,
    instagram_url: null,
    facebook_url: null,
    has_website: false,
    area: '那覇市',
    source: 'manual',
    raw_payload: {},
  },
  {
    place_id: 'dummy-002',
    name: 'ヘアサロン ソレイユ',
    category: '美容室',
    address: '沖縄県浦添市城間1-2-3',
    phone: '098-222-0002',
    opening_hours: { weekday_text: ['月曜日: 10:00–19:00', '火曜日: 定休日', '水曜日: 10:00–19:00', '木曜日: 10:00–19:00', '金曜日: 10:00–20:00', '土曜日: 9:00–19:00', '日曜日: 9:00–18:00'] },
    rating: 4.6,
    review_count: 142,
    photo_count: 18,
    website_url: null,
    instagram_url: 'https://www.instagram.com/soleil_hair/',
    facebook_url: null,
    has_website: false,
    area: '浦添市',
    source: 'manual',
    raw_payload: {},
  },
  {
    place_id: 'dummy-003',
    name: 'リゾートスパ ちゅら',
    category: 'スパ',
    address: '沖縄県恩納村前兼久3-4-5',
    phone: '098-333-0003',
    opening_hours: { weekday_text: ['毎日: 10:00–22:00'] },
    rating: 4.7,
    review_count: 203,
    photo_count: 45,
    website_url: 'https://chura-spa.example.com',
    instagram_url: 'https://www.instagram.com/chura_spa/',
    facebook_url: null,
    has_website: true,
    area: '恩納村',
    source: 'manual',
    raw_payload: {},
  },
  {
    place_id: 'dummy-004',
    name: '石垣牛焼肉 まきし',
    category: '飲食店',
    address: '沖縄県石垣市美崎町1-5',
    phone: '0980-444-0004',
    opening_hours: { weekday_text: ['火曜日〜日曜日: 17:00–23:00', '月曜日: 定休日'] },
    rating: 4.5,
    review_count: 156,
    photo_count: 32,
    website_url: null,
    instagram_url: null,
    facebook_url: null,
    has_website: false,
    area: '石垣市',
    source: 'manual',
    raw_payload: {},
  },
  {
    place_id: 'dummy-005',
    name: 'ネイルアート moana',
    category: 'ネイルサロン',
    address: '沖縄県北谷町美浜2-3-6',
    phone: '098-555-0005',
    opening_hours: { weekday_text: ['月曜日: 10:00–19:00', '火曜日: 定休日', '水曜日〜日曜日: 10:00–19:00'] },
    rating: 4.8,
    review_count: 98,
    photo_count: 61,
    website_url: null,
    instagram_url: 'https://www.instagram.com/moana_nail/',
    facebook_url: 'https://www.facebook.com/moana.nail',
    has_website: false,
    area: '北谷町',
    source: 'manual',
    raw_payload: {},
  },
  {
    place_id: 'dummy-006',
    name: '内科クリニック なは',
    category: '医院',
    address: '沖縄県那覇市首里石嶺町1-1-1',
    phone: '098-666-0006',
    opening_hours: { weekday_text: ['月〜金: 9:00–12:30, 14:30–18:00', '土: 9:00–12:30', '日・祝: 休診'] },
    rating: 3.9,
    review_count: 34,
    photo_count: 5,
    website_url: null,
    instagram_url: null,
    facebook_url: null,
    has_website: false,
    area: '那覇市',
    source: 'manual',
    raw_payload: {},
  },
  {
    place_id: 'dummy-007',
    name: '古民家ゲストハウス 島時間',
    category: 'ゲストハウス',
    address: '沖縄県読谷村座喜味4-5-6',
    phone: '098-777-0007',
    opening_hours: null,
    rating: 4.4,
    review_count: 67,
    photo_count: 28,
    website_url: null,
    instagram_url: null,
    facebook_url: null,
    has_website: false,
    area: '読谷村',
    source: 'manual',
    raw_payload: {},
  },
  {
    place_id: 'dummy-008',
    name: '琉球カフェ てぃーだ',
    category: 'カフェ',
    address: '沖縄県宮古島市平良下里3-7-2',
    phone: '0980-888-0008',
    opening_hours: { weekday_text: ['毎日: 8:00–18:00', '水曜日: 定休日'] },
    rating: 4.2,
    review_count: 45,
    photo_count: 19,
    website_url: null,
    instagram_url: 'https://www.instagram.com/tiida_cafe/',
    facebook_url: null,
    has_website: false,
    area: '宮古島市',
    source: 'manual',
    raw_payload: {},
  },
]
