/**
 * 生成物から、公開可能な単体HTMLドキュメントを組み立てる。
 * 将来の「公開自動化」（静的ホスティング等）でそのまま配信できるよう、
 * 外部ビルドパイプライン非依存（Tailwind CDN + インラインCSS）で完結させる。
 */
import type { GeneratedWebsiteContents, StoreBrief } from "@/lib/types";

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function nl2br(input: string): string {
  return escapeHtml(input).replace(/\n/g, "<br />");
}

export function renderWebsitePreviewHtml(brief: StoreBrief, contents: GeneratedWebsiteContents): string {
  const sections = contents.sections
    .map(
      (s) => `
    <section class="section">
      <h2>${escapeHtml(s.heading)}</h2>
      <p>${nl2br(s.body)}</p>
    </section>`
    )
    .join("\n");

  const faq = contents.faq
    .map(
      (f) => `
      <div class="faq-item">
        <p class="faq-q">Q. ${escapeHtml(f.question)}</p>
        <p class="faq-a">A. ${escapeHtml(f.answer)}</p>
      </div>`
    )
    .join("\n");

  const gbp = contents.googleBusinessImprovement.map((g) => `<li>${escapeHtml(g)}</li>`).join("\n");

  return `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(contents.seoTitle)}</title>
<meta name="description" content="${escapeHtml(contents.metaDescription)}" />
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { margin: 0; font-family: "Hiragino Sans", "Noto Sans JP", system-ui, sans-serif; color: #1f2330; background: #fafafa; line-height: 1.8; }
  .hero { padding: 72px 24px; text-align: center; background: linear-gradient(135deg, #4c1d95, #6d28d9); color: #fff; }
  .hero h1 { font-size: clamp(28px, 5vw, 44px); margin: 0 0 16px; }
  .hero p { font-size: 18px; opacity: 0.92; margin: 0; }
  .concept { max-width: 720px; margin: 32px auto; padding: 0 24px; text-align: center; color: #4b5563; }
  main { max-width: 860px; margin: 0 auto; padding: 0 24px 64px; }
  .section { margin: 40px 0; padding: 24px; background: #fff; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }
  .section h2 { margin-top: 0; color: #4c1d95; }
  .cta { max-width: 860px; margin: 0 auto 64px; padding: 40px 24px; text-align: center; background: #ede9fe; border-radius: 16px; }
  .cta h3 { margin: 0 0 8px; font-size: 24px; }
  .cta .btn { display: inline-block; margin-top: 16px; padding: 12px 32px; background: #5b21b6; color: #fff; border-radius: 999px; text-decoration: none; font-weight: 600; }
  .faq-item { margin-bottom: 16px; }
  .faq-q { font-weight: 700; margin: 0 0 4px; }
  .faq-a { margin: 0; color: #4b5563; }
  footer { text-align: center; padding: 24px; color: #9ca3af; font-size: 13px; }
</style>
</head>
<body>
  <div class="hero">
    <h1>${escapeHtml(contents.heroTitle)}</h1>
    <p>${escapeHtml(contents.heroSubtitle)}</p>
  </div>
  <p class="concept">${escapeHtml(contents.concept)}</p>
  <main>
    ${sections}
    <section class="section">
      <h2>よくある質問</h2>
      ${faq}
    </section>
    <section class="section">
      <h2>Googleビジネスプロフィール改善案</h2>
      <ul>${gbp}</ul>
    </section>
  </main>
  <div class="cta">
    <h3>${escapeHtml(contents.cta.headline)}</h3>
    <p>${escapeHtml(contents.cta.body)}</p>
    <a class="btn" href="#contact">${escapeHtml(contents.cta.buttonLabel)}</a>
  </div>
  <footer>Generated by Neumos AI for ${escapeHtml(brief.storeName)}</footer>
</body>
</html>`;
}
